steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/market_data_collection:$COMMIT_SHA',
         '-f', 'Dockerfile',
         '.']
images:
- '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/market_data_collection:$COMMIT_SHA'
